services:
  - type: web
    name: ilivre-app
    runtime: php
    plan: free
    buildCommand: "./build.sh"
    startCommand: "php artisan serve --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DB_HOST
        value: #
      - key: DB_DATABASE
        value: defaultdb
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        value: #
      - key: APP_KEY
        generate: true